<main>
            <section class="left_column">
                <p>Colonne Gauche</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, corrupti velit beatae veniam id quod eveniet voluptates consequatur quo similique odio autem excepturi repellat laudantium fugiat non minima laborum cum eligendi? Eum magnam pariatur, blanditiis quod earum vero provident ducimus. Recusandae, est nemo exercitationem expedita, consectetur repudiandae, modi laborum soluta illo neque pariatur repellat quisquam dolorum atque minus et ex ullam provident non numquam corporis. Iusto inventore, voluptatum accusamus tenetur ex reiciendis, tempora a saepe, deleniti amet aperiam vero. Sunt tempore ad, asperiores ipsam maiores totam dolores fugiat adipisci magni ab unde quidem sed eligendi quam, quis illum in eaque.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, corrupti velit beatae veniam id quod eveniet voluptates consequatur quo similique odio autem excepturi repellat laudantium fugiat non minima laborum cum eligendi? Eum magnam pariatur, blanditiis quod earum vero provident ducimus. Recusandae, est nemo exercitationem expedita, consectetur repudiandae, modi laborum soluta illo neque pariatur repellat quisquam dolorum atque minus et ex ullam provident non numquam corporis. Iusto inventore, voluptatum accusamus tenetur ex reiciendis, tempora a saepe, deleniti amet aperiam vero. Sunt tempore ad, asperiores ipsam maiores totam dolores fugiat adipisci magni ab unde quidem sed eligendi quam, quis illum in eaque.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, corrupti velit beatae veniam id quod eveniet voluptates consequatur quo similique odio autem excepturi repellat laudantium fugiat non minima laborum cum eligendi? Eum magnam pariatur, blanditiis quod earum vero provident ducimus. Recusandae, est nemo exercitationem expedita, consectetur repudiandae, modi laborum soluta illo neque pariatur repellat quisquam dolorum atque minus et ex ullam provident non numquam corporis. Iusto inventore, voluptatum accusamus tenetur ex reiciendis, tempora a saepe, deleniti amet aperiam vero. Sunt tempore ad, asperiores ipsam maiores totam dolores fugiat adipisci magni ab unde quidem sed eligendi quam, quis illum in eaque.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, corrupti velit beatae veniam id quod eveniet voluptates consequatur quo similique odio autem excepturi repellat laudantium fugiat non minima laborum cum eligendi? Eum magnam pariatur, blanditiis quod earum vero provident ducimus. Recusandae, est nemo exercitationem expedita, consectetur repudiandae, modi laborum soluta illo neque pariatur repellat quisquam dolorum atque minus et ex ullam provident non numquam corporis. Iusto inventore, voluptatum accusamus tenetur ex reiciendis, tempora a saepe, deleniti amet aperiam vero. Sunt tempore ad, asperiores ipsam maiores totam dolores fugiat adipisci magni ab unde quidem sed eligendi quam, quis illum in eaque.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, corrupti velit beatae veniam id quod eveniet voluptates consequatur quo similique odio autem excepturi repellat laudantium fugiat non minima laborum cum eligendi? Eum magnam pariatur, blanditiis quod earum vero provident ducimus. Recusandae, est nemo exercitationem expedita, consectetur repudiandae, modi laborum soluta illo neque pariatur repellat quisquam dolorum atque minus et ex ullam provident non numquam corporis. Iusto inventore, voluptatum accusamus tenetur ex reiciendis, tempora a saepe, deleniti amet aperiam vero. Sunt tempore ad, asperiores ipsam maiores totam dolores fugiat adipisci magni ab unde quidem sed eligendi quam, quis illum in eaque.</p>
                
            </section>